services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - local-db:/var/lib/mysql
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$${MYSQL_ROOT_PASSWORD}' ]
      interval: 10s
      timeout: 2s
      retries: 100
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul

  blog:
    image: openjdk:11-jre
    volumes:
      - "/build/libs:/app"
    entrypoint: [ "java", "-jar", "/app/blog-0.0.1-SNAPSHOT.jar" ]
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      MYSQL_HOST: mysql

  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"

volumes:
  local-db:
